### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by oysstu** [GPflow/check_shapes#35]
Package does not build for Python 3.11 due to the following line in pyproject.toml.
https://github.com/GPflow/check_shapes/blob/396911043a723cb36e81f7abd85f59c04c83e376/pyproject.toml#L35

Are there any known issues with 3.11?

**Comment by jesnie** [comment]
Sorry about the late reply. If I remember correctly it's because some downstream package has (or had, at the time) that constraint, and `poetry` won't let us depend on it without that constraint ourselves. It can probably be relaxed now.
