### ISSUE TITLE
`check_shapes` too noisy in tracebacks

### ISSUE THREAD

**Issue by Corwinpro** [GPflow/check_shapes#36]
I can see (way too) many occurrences of entries like

```
File "/opt/venv/lib/python3.10/site-packages/check_shapes/integration/tf.py", line 60, in wrapped_method * return wrapped_function(self, *args, **kwargs)
```

and similar in tracebacks of functions that are wrapped in `check_shapes` . Can we update `check_shapes` with (I guess?) something like `functools.wraps` to not see this? It is very annoying and uninformative.

Thank you very much!

**Comment by jesnie** [comment]
I'd love to filter those out, but I don't know how to do it. I'm pretty sure `functools.wraps` doesn't do that. We already use `functools.update_wrapper`, which should do the same thing: https://github.com/GPflow/check_shapes/blob/396911043a723cb36e81f7abd85f59c04c83e376/check_shapes/decorator.py#L196

**Comment by jesnie** [comment]
This might hold a solution: https://stackoverflow.com/questions/72146438/remove-decorator-from-stack-trace
